version: '3.9'

services:
  sound-localization-tester-backend:
    container_name: sound-localization-tester-backend
    build: .
    environment:
      app__cors: true
      surreal_db__address: ws://surrealdb:8000
      auth_keys__encoding: devkeys/jwt-auth-rsa.key
      auth_keys__decoding: devkeys/jwt-auth-rsa.key.pub
      admin__username: root
      admin__password: root
    ports:
      - 3000:3000
    volumes:
      - ./devkeys:/app/devkeys

  sound-localization-tester-database:
    container_name: sound-localization-tester-database
    hostname: surrealdb
    build: src/services/database
    ports:
      - 8000:8000
    volumes:
      - surrealdb_volume:/data

volumes:
  surrealdb_volume:
