version: '3.9'

services:
  sound-localization-tester-backend:
    container_name: sound-localization-tester-backend
    build: .
    environment:
      app__endpoint: 0.0.0.0:3000
      app__permissive_cors: true
      database__address: ws://database:8000
      auth_keys__encoding: devkeys/jwt-auth-rsa.key
      auth_keys__decoding: devkeys/jwt-auth-rsa.key.pub
      admin__username: root
      admin__password: root
    ports:
      - 3000:3000
    volumes:
      - ./devkeys:/app/devkeys
      - ./migrations:/app/migrations
      - file_storage_volume:/app/file_storage
    depends_on:
      sound-localization-tester-database:
        condition: service_healthy

  sound-localization-tester-database:
    container_name: sound-localization-tester-database
    hostname: database
    build: src/services/database
    ports:
      - 8000:8000
    volumes:
      - database_volume:/data
    healthcheck:
      test: [ "CMD", "/surreal", "isready" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  file_storage_volume:
  database_volume:
